### PR TITLE
1.0.0.0-rc2

### PR DESCRIPTION
**Pull request by morning4coffe-dev**
GitHub Issue (If applicable): closes https://github.com/morning4coffe-dev/recurrents/issues/93, closes https://github.com/morning4coffe-dev/recurrents/issues/91

The last rc version before v1.0

TODO:
- [x] Add https://github.com/morning4coffe-dev/recurrents/issues/93
- [x] Fix https://github.com/morning4coffe-dev/recurrents/issues/91
- [ ] Add https://github.com/morning4coffe-dev/recurrents/issues/90
- [x] Remove https://github.com/morning4coffe-dev/recurrents/issues/75
- [ ] Refactor some parts of the UI
- [ ] Improve performance
- [ ] Windows Rating pop-up

### CODE REVIEW

**Review by szv — COMMENTED** [review]
What do you think about this idea 🤔 (regarding f00b9eb):

Converter
```C#
public class PaymentPeriodToLocalizedStringConverter : IValueConverter
{
    private IStringLocalizer _localizer;

    public PaymentPeriodToLocalizedStringConverter()
    {
        _localizer = App.Services!.GetRequiredService<IStringLocalizer>();
    }

    public object? Convert(object value, Type targetType, object parameter, string language)
    {
        if (value is Period period)
        {
            return _localizer[period.ToString()].Value;
        }

        return value;
    }

    public object? ConvertBack(object value, Type targetType, object parameter, string language)
    {
        throw new NotImplementedException();
    }
}
```

ItemDetails.cs-Z.281
```XAML
<ComboBox VerticalAlignment="Bottom"
          ItemsSource="{toolkit:EnumValues Type=models:Period}"
          SelectedItem="{x:Bind ViewModel.EditItem.Billing.PeriodType, Mode=TwoWay}"
          MinWidth="120"
          Grid.Column="1">
  <ComboBox.ItemTemplate>
    <DataTemplate x:DataType="models:Period">
      <TextBlock Text="{x:Bind Converter={StaticResource PaymentPeriodToLocalizedStringConverter}}" />
    </DataTemplate>
  </ComboBox.ItemTemplate>
</ComboBox>
```

**Comment by morning4coffe-dev** [comment]
@szv Oh yes! I didn't realize this solution at the time, but your solution sounds much better than the current one. Thank you, I will test it out when I am back home.

**Comment by szv** [comment]
Great :)

**Comment by morning4coffe-dev** [comment]
@szv I noticed that you have already (maybe accidentally ;)) partially added it [here](https://github.com/morning4coffe-dev/recurrents/pull/102/files#diff-603537fd799d46da3ccef1bb106533a5c48e6ff97395667cc852c106f0bcbd61R286-R291) as part of #102. It is not an issue, I just made a quick fix #103 as it was missing the Converter, but this feature is now on master. Thanks for your contribution! 🚀

**Comment by szv** [comment]
Ah ok sorry. Yes that was unintentionally. 😬

**Comment by morning4coffe-dev** [comment]
Some of the changes created a large conflicts. Closing in favor of cherry-picking the newly added commits directly to main.

**Pull request closed without merging**
